### ISSUE TITLE
G2 cameras cause deserialization to fail when building IspSettings

### ISSUE THREAD

**Issue by patrickhampson** [i8beef/I8Beef.UniFi.Video#2]
When deserializing  the IspSettings object on a G2 camera, a few of the properties are null.  These will fail to deserialize and throw an exception.  We should probably change these to nullable types.

`"ispSettings": {
            "brightness": 50,
            "contrast": 50,
            "denoise": 50,
            "hue": 50,
            "saturation": 50,
            "sharpness": 50,
            "flip": 0,
            "mirror": 0,
            "gamma": null,
            "wdr": 1,
            "aeMode": "auto",
            "irLedMode": "auto",
            "irLedLevel": 215,
            "focusMode": "ztrig",
            "focusPosition": 0,
            "zoomPosition": 0,
            "icrSensitivity": 0,
            "aggressiveAntiFlicker": 0,
            "enable3dnr": 1,
            **"dZoomStreamId": null,
            "dZoomCenterX": null,
            "dZoomCenterY": null,
            "dZoomScale": null,
            "lensDistortionCorrection": null,
            "enableExternalIr": null,**
            "touchFocusX": 0,
            "touchFocusY": 0,
            "irOnValBrightness": 50,
            "irOnStsBrightness": 0,
            "irOnValContrast": 50,
            "irOnStsContrast": 0,
            "irOnValDenoise": 50,
            "irOnStsDenoise": 0,
            "irOnValHue": 50,
            "irOnStsHue": 0,
            "irOnValSaturation": 50,
            "irOnStsSaturation": 0,
            "irOnValSharpness": 50,
            "irOnStsSharpness": 0
          }`

**Comment by i8beef** [comment]
Go ahead and put it in your other PR with those other changes, and Ill review / approve it.

**Comment by i8beef** [comment]
Approved and merged.
